### ISSUE TITLE
TypedArray.from() error in Safari

### ISSUE THREAD

**Issue by sparrow522** [WebReflection/uint8-to-base64#2]
Hello, thanks for the great library.
As in the title, calling something like
Uint8Array.from([1,2])
raises this error in Safari:
TypeError: TypedArray.from requires its this argument subclass a TypedArray constructor

Safari version: 13.1.2
uint8-to-base64 version: 0.2.0

**Comment by WebReflection** [comment]
I can't verify this on GNOME Web but it looks like you confused this module with the WebKit project ... maybe you should file a bug for Safari?

**Comment by sparrow522** [comment]
I modified the source code in my project and it runs correctly, maybe the safari environment is polluted.
